version: "3"

networks:
  appservers:

volumes:
  system:
  backup:
  database:
  pgadmin:

services:
  db:
    image: postgres:10-alpine
    environment:
      POSTGRES_PASSWORD: mete
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      appservers:
        aliases:
          - db

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: max.staff@gmx.de
      PGADMIN_DEFAULT_PASSWORD: affenstark
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin:/root/.pgadmin
    restart: on-failure
    networks:
      appservers:
        aliases:
          - pgadmin
    depends_on:
      - db
    ports:
      - "82:80"

  db-backup:
    image: nomaster/postgres-backup
    environment:
      PGPASSWORD: mete
    volumes:
      - backup:/backup
    restart: on-failure
    networks:
      appservers:
    depends_on:
      - db

  backend:
    environment:
      RAILS_ENV: production
      SENTRY_DSN:
    image: maxmatti/mete
    volumes:
      - system:/app/public/system
    restart: on-failure
    networks:
      appservers:
        aliases:
          - app
    depends_on:
      - db
    ports:
      - "81:80"
