version: "3"

networks:
  metenetwork:

volumes:
  system:
  backup:
  database:
  pgadmin:

services:
  db:
    image: postgres:10-alpine
    environment:
      POSTGRES_PASSWORD: mete
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      metenetwork:
        aliases:
          - db

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: 'max.staff@gmx.de'
      PGADMIN_DEFAULT_PASSWORD: 'affenstark'
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin:/root/.pgadmin
    restart: on-failure
    ports:
      - "82:80"
    networks:
      metenetwork:
    depends_on:
      - db

  db-backup:
    image: nomaster/postgres-backup
    environment:
      PGPASSWORD: mete
    volumes:
      - backup:/backup
    restart: on-failure
    networks:
      metenetwork:
    depends_on:
      - db

  backend:
    environment:
      RAILS_ENV: production
      SENTRY_DSN:
    build:
      context: .
      dockerfile: Dockerfile
    image: chaosdorf/mete
    build: .
    volumes:
      - system:/app/public/system
    restart: on-failure
    networks:
      metenetwork:
        aliases:
          - app
    depends_on:
      - db
    ports:
      - "81:80"
